# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_pizza_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Pizza', verbose_name='Пицца')),
            ],
            options={
                'verbose_name': 'Заказ пиццы',
                'verbose_name_plural': 'Заказы пицц',
            },
        ),
    ]
